# -*- coding: utf-8 -*-
"""English-to-French Translation Chatbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6wQCMmhYG_v1X4AdlmKtytR_ckGR04y
"""

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import sys
import time

print("Loading model... (this may take a few seconds)")

model_name = "Helsinki-NLP/opus-mt-en-fr"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

print("Model loaded successfully!")

def typing_effect(text, speed=0.03):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(speed)
    print()

def chatbot():
    print("\nEnglish-to-French Translation Chatbot")
    print("Type 'exit' to quit.\n")

    while True:
        user_input = input("You (English): ").strip()

        if user_input.lower() in ("exit", "quit", "bye", "goodbye"):
            print("Bot: Goodbye! 👋")
            break

        if not user_input:
            continue

        inputs = tokenizer(user_input, return_tensors="pt")
        outputs = model.generate(**inputs)

        french_text = tokenizer.decode(
            outputs[0],
            skip_special_tokens=True
        )

        print("Bot (French): ", end="")
        typing_effect(french_text)

if __name__ == "__main__":
    chatbot()